SCRIPTS=	pfwsense.sh pfwsense-import.sh pfwsense-install.sh \
		pfwsense-reset.sh pfwsense-rootpass.sh pfwsense-ufs.sh \
		pfwsense-zfs.sh pfwsense.subr.sh

MAN=		# not needed

PREFIX?=${DESTDIR}/usr

BINDIR=	${PREFIX}/libexec/bsdinstall

.include <bsd.prog.mk>
